query Page($skip: Int, $limit: Int, $where: PlanInputFilter){
  result: planPage(skip: $skip, limit: $limit, where: $where) {
		...Plan    
  }
}

fragment Plan on PlanGQLModel {
  __typename
    id
    lastchange
    name
    lessons {
      name
      id
      order
      type {
        id
      }
      length
      users {
        id
      }
      groups {
        id
      }
      facilities {
        id
      }
    }
    semester {
      id
      plans {
        id
      }
    }
}