query Page($skip: Int, $limit: Int, $where: PlannedLessonInputFilter){
  result: plannedLessonPage(skip: $skip, limit: $limit, where: $where) {
    ...Lesson
  }
}

fragment Lesson on PlannedLessonGQLModel {
  __typename
    id
    name
  lastchange
  rbacObject { id }
  type { id }
  order
  length
  linkedTo { __typename id name }
  linkedWith { __typename id name }
  users { id }
  groups { id }
  facilities { id }
  event { id }
  semester { id }
  plan { __typename id name }
}