

query plannedLessonById($id: UUID!) {
  plannedLessonById(id: $id) {
    __typename
    id
    name
    lastchange
    created
    createdby {
      id
    }
    changedby {
      id
    }
    rbac_object {
      id
    }
    order
    length
    type {
      id
    }
    linked_to {
      id
    }
    linked_with {
      id
    }
    users {
      id
    }
    groups {
      id
    }
    facilities {
      id
    }
    event {
      id
    }
    topic {
      id
    }
    semester {
      id
    }
    plan {
      id
    }
  }
}

