

mutation ($id: UUID!, $lastchange: DateTime!, $name: String) {
  result: plannedLessonUpdate(
    lesson: {
      id: $id,
      lastchange: $lastchange,
      name: $name
    }
  ) {
    __typename
  }
}
