
mutation ($id: UUID!, $lastchange: DateTime!, $name: String!, $length: Int, $startproposal: DateTime, $order: Int, $linkedlesson_id: UUID, $topic_id: UUID, $lessontype_id: UUID, $semester_id: UUID, $event_id: UUID) {
  result: plannedLessonUpdate(
    lesson: {
      id: $id,
      lastchange: $lastchange,
      name: $name,
      length: $length,
      startproposal: $startproposal,
      order: $order,
      linkedlesson_id: $linkedlesson_id,
      topic_id: $topic_id,
      lessontype_id: $lessontype_id,
      semester_id: $semester_id,
      event_id: $event_id
    }
  ) {
    __typename
    ...Error
    ...PlannedLesson
  }
}

fragment Error on PlannedLessonUpdateError {
	__typename
  failed
}

fragment PlannedLesson on PlannedLessonGQLModel {
  id
  lastchange
  name
}