mutation ($name: String!, $semesterId: UUID!, $mastereventId: UUID!) {
  result: planInsert(
    plan: {
      name: $name,
      semesterId: $semesterId,
      mastereventId: $mastereventId,
    }
  ) {
    __typename
  }
}