mutation ($id: UUID, $name: String!) {
  result: facilityTypeInsert(
    facilityType: {id: $id, name: $name}
  ) {
    __typename
    ...Error
    ...Facility
  }
}

mutation ($name: String!, $description: String, $startdate: DateTime, $enddate: DateTime) {
  result: planInsert(
    plan: {
      name: $name,
      description: $description,
      startdate: $startdate,
      enddate: $enddate
    }
  ) {
    __typename
    ...Error
    ...Plan
  }
}

fragment Error on InsertError {
	__typename
	msg
}

fragment Facility on FacilityTypeGQLModel {
  id
  lastchange
  name
  nameEn
}

fragment Plan on PlanGQLModel {
  id
  name
  description
  startdate
  enddate
}
