
mutation ($name: String!, $semesterId: UUID!, $mastereventId: UUID!) {
  result: planInsert(
    plan: {
      name: $name,
      semesterId: $semesterId,
      mastereventId: $mastereventId,
    }
  ) {
    __typename
    ...Plan
    ...on InsertError {
      failed
      input
      msg
    }
  }
}


fragment	Plan on PlanGQLModel {
  __typename
  id
  lastchange
  name
  
}