mutation ($id: UUID!, $lastchange: DateTime!) {
  result: facilityTypeDelete(
    facilityType: {id: $id, lastchange: $lastchange}
  ) {
    __typename
    ...Error
  }
}

mutation ($id: UUID!, $lastchange: DateTime!) {
  result: planDelete(
    plan: {id: $id, lastchange: $lastchange}
  ) {
    __typename
    ...Error
  }
}

fragment Error on FacilityTypeGQLModelDeleteError {
	__typename
  failed
  msg
}

fragment Error on PlanDeleteError {
	__typename
  failed
  msg
}
