mutation DeletePlan($id: UUID!, $lastchange: DateTime!) {
  planDelete(
    plan: { id: $id, lastchange: $lastchange }
  ) {
    __typename
    ...Error
  }
}

fragment Error on PlanGQLModelDeleteError {
  msg
  input
  failed
  Entity {
    id
    lastchange
  }
}