
mutation deletePlan($id: UUID!, $lastchange: DateTime!) {
  deletePlan(input: {id: $id, lastchange: $lastchange}) {
    plan {
      id
      lastchange
    }
    errors {
      message
      Entity{
        id
        lastchange
      }
    }
  }
}