
query planPage($skip: Int = 0, $limit: Int = 10, $where: PlanInputFilter) {
  planPage(skip: $skip, limit: $limit, where: $where) {
    ...Plan
  }
}

fragment	Plan on PlanGQLModel {
  __typename
  id
  lastchange
  name
}