query planById($id: UUID!) {
  planById(id: $id) {
    __typename
    id
    name
    lastchange
  }
}

query read($id: UUID!) {
  result: planById(id: $id) {
    __typename
    id
    name
    lastchange
  }
}
