query ftid($id: UUID!){
  facilityTypeById(id: $id) {
    __typename
    id
    name
    nameEn
    lastchange
  }
}

query planById($id: UUID!) {
  planById(id: $id) {
    __typename
    id
    name
    description
    startdate
    enddate
  }
}

fragment Plan on PlanGQLModel{
  __typename
  id
  name
  description
  startdate
  enddate
}
